#!/usr/bin/env python3
"""
sharp.processing.build_processed_data

Stage-0 raw-data ETL: turns the lab's raw sensor/annotation exports
(`raw_data/`) into the analysis-ready tables under `processed_data/`
that every downstream module in this package reads from.

It stitches together, per session (date + room):
  - EDA        : locates each participant's Shimmer GSR3+ raw file via the
                 Host Sheet -> Device ID Records -> hardware_id chain, and
                 copies/pointer-indexes the NeuroKit2-filtered output.
  - Video/task
    timing     : resolves each processed task video's real-world start/end
                 time from the Sync sheet, and the trigger-video frame
                 offsets (CT/ET1/ET2) from the timepoint sheet.
  - EmoNet     : maps each participant's per-second facial-affect file to
                 its (date, color, hardware_id) identity.
  - Gaze       : builds group-level gaze event tables and a group/date-key map.
  - Transcripts: deduplicates and indexes per-session transcript sources.

Requires access to the raw MSSRL sensor exports (`raw_data/`), which are
NOT included in this repository (see the top-level README's "Data
availability" section) -- this module is included for pipeline
transparency, not as something an external reader can run standalone.
The rest of the `sharp.processing` package contains the actual
per-modality parsing logic; this file is only the orchestration entry
point (run as `python -m sharp.processing.build_processed_data`).

Output: processed_data/ (see the generated processed_data/README.md for
the full table of output files).
"""
from __future__ import annotations

import shutil

from .config import PROCESSED_ROOT
from .eda import copy_eda_outputs
from .education import process_education_data
from .gaze import process_gaze_data
from .mapping import (
    build_device_id_records,
    build_emotion_origin_map,
    build_host_device_schedule,
    build_identity_links,
    build_oct_timepoint_rows,
    build_sync_timing_rows,
    build_trigger_emotion_rows,
    build_video_timing_rows,
    patch_trigger_unix_ms,
)
from .reporting import write_eda_outputs, write_gaze_outputs, write_readme, write_trigger_emotion_outputs
from .transcripts import process_transcripts


def _clean_processed_root() -> None:
    """
    Wipe PROCESSED_ROOT but preserve processed_data/eda/filtered/ and scr/
    (generated by process_eda_all.py — expensive to regenerate, ~45 GB each).
    """
    EDA_KEEP = {"filtered", "scr"}
    if not PROCESSED_ROOT.exists():
        PROCESSED_ROOT.mkdir(parents=True)
        return
    for item in PROCESSED_ROOT.iterdir():
        if item.name == "eda" and item.is_dir():
            for subitem in item.iterdir():
                if subitem.name not in EDA_KEEP:
                    shutil.rmtree(subitem) if subitem.is_dir() else subitem.unlink()
        else:
            shutil.rmtree(item) if item.is_dir() else item.unlink()
    (PROCESSED_ROOT / "eda").mkdir(exist_ok=True)
    (PROCESSED_ROOT / "eda" / "filtered").mkdir(exist_ok=True)
    (PROCESSED_ROOT / "eda" / "scr").mkdir(exist_ok=True)


def main() -> None:
    _clean_processed_root()

    eda_manifest, eda_session_rows = copy_eda_outputs()
    host_rows = build_host_device_schedule()
    emotion_origin_rows = build_emotion_origin_map()
    device_id_rows, global_hardware_map = build_device_id_records()
    sync_timing_rows = build_sync_timing_rows()
    oct_timepoint_rows = build_oct_timepoint_rows()
    identity_rows = build_identity_links(host_rows, emotion_origin_rows, device_id_rows, global_hardware_map)
    trigger_emotion_rows = build_trigger_emotion_rows(identity_rows)
    video_timing_rows = build_video_timing_rows(
        host_rows,
        identity_rows,
        sync_timing_rows,
        device_id_rows,
        global_hardware_map,
        eda_session_rows=eda_session_rows,
    )
    patch_trigger_unix_ms(video_timing_rows, trigger_emotion_rows)

    write_trigger_emotion_outputs(trigger_emotion_rows)
    write_eda_outputs(
        eda_manifest,
        eda_session_rows,
        host_rows,
        device_id_rows,
        emotion_origin_rows,
        sync_timing_rows,
        oct_timepoint_rows,
        video_timing_rows,
    )

    gaze_summary_rows, gaze_group_rows = process_gaze_data(sync_timing_rows, video_timing_rows)
    write_gaze_outputs(gaze_summary_rows, gaze_group_rows)

    transcript_manifest = process_transcripts(sync_timing_rows)
    edu_manifest = process_education_data()

    write_readme(
        eda_manifest,
        transcript_manifest,
        edu_manifest,
        eda_session_rows,
        host_rows,
        device_id_rows,
        sync_timing_rows,
        oct_timepoint_rows,
        video_timing_rows,
        gaze_summary_rows,
        gaze_group_rows,
    )


if __name__ == "__main__":
    main()
